export { default } from "./lectors";
export { default as EditTraining } from "./edit-training";
export { default as EditLectures } from "./edit-lectures";
export { default as EditLecture } from "./edit-lecture";
export { default as CreateTraining } from "./create-training";
export { default as CreateLectures } from "./edit-lectures";
export { default as CreateLecture } from "./create-lecture";
export { default as DeleteLecture } from "./delete-lecture";
export { default as AddLecture } from "./add-lecture";
export { default as CreateTrainingUpload } from "./create-training-upload";
