const env = import.meta.env ?? {};

export const GRAPHQL_URI = env.VITE_GRAPHQL_URI;
export const PROVISIONING_URI = env.VITE_PROVISIONING_URI || "/provisioning";
export const PROVISIONING_API = env.VITE_PROVISIONING_API || "/provisioning";
export const OIDC_LOGIN_URI = env.VITE_OIDC_LOGIN || "/login";
export const AUTH_SESSION_URI = env.VITE_AUTH_SESSION_URI || "/auth/session";
export const AVATAR_UPLOAD_URI = env.VITE_AVATAR_UPLOAD_URI;
export const AVATAR_DELETE_URI = env.VITE_AVATAR_DELETE_URI;
export const TRAINING_UPLOAD_URI = env.VITE_TRAINING_UPLOAD_URI;
export const TRAINING_DELETE_URI = env.VITE_TRAINING_DELETE_URI;
export const HOMEWORK_FILE_UPLOAD_URI = env.VITE_HOMEWORK_FILE_UPLOAD_URI;
export const HOMEWORK_FILE_GET_URI = env.VITE_HOMEWORK_FILE_GET_URI;
export const HOMEWORK_FILE_DELETE_URI = env.VITE_HOMEWORK_FILE_DELETE_URI;
export const LECTURE_FILE_UPLOAD_URI = env.VITE_LECTURE_FILE_UPLOAD_URI;
export const LECTURE_FILE_GET_URI = env.VITE_LECTURE_FILE_GET_URI;
export const LECTURE_FILE_DELETE_URI = env.VITE_LECTURE_FILE_DELETE_URI;
export const LECTURE_HOMEWORK_FILE_UPLOAD_URI =
  env.VITE_LECTURE_HOMEWORK_FILE_UPLOAD_URI;
export const LECTURE_HOMEWORK_FILE_GET_URI =
  env.VITE_LECTURE_HOMEWORK_FILE_GET_URI;
export const LECTURE_HOMEWORK_FILE_DELETE_URI =
  env.VITE_LECTURE_HOMEWORK_FILE_DELETE_URI;
export const HOMEWORK_COMMENT_FILE_UPLOAD_URI =
  env.VITE_HOMEWORK_COMMENT_FILE_UPLOAD_URI;
export const HOMEWORK_COMMENT_FILE_GET_URI =
  env.VITE_HOMEWORK_COMMENT_FILE_GET_URI;
export const HOMEWORK_COMMENT_FILE_DELETE_URI =
  env.VITE_HOMEWORK_COMMENT_FILE_DELETE_URI;
