name: frontend_deploy_test
on:
  push:
    branches:
      - develop
jobs:
  yarn-and-node:
    runs-on: stage-runner
    env:
      HUSKY: "0"
    steps:
      - uses: actions/checkout@v7
      - name: Use Node.js 26
        uses: actions/setup-node@v6
        with:
          node-version: 26
      - name: Run install
        uses: borales/actions-yarn@v4
        with:
          cmd: install
      - name: Run build
        uses: borales/actions-yarn@v4
        with:
          cmd: build
      - name: Deploy step 1
        run: rm -rf /var/www/app-stage.qa.guru/html/*
      #            cp -r dist/* /var/www/app.qa.guru/html/
      - name: Deploy step 2
        run:
          #            rm -rf /var/www/app.qa.guru/html/*
          cp -r dist/* /var/www/app-stage.qa.guru/html/

  runtest_jenkins:
    runs-on: stage-runner
    needs: yarn-and-node
    steps:
      - name: jenkins
        run: curl -X POST "https://jenkins.autotests.cloud/buildByToken/buildWithParameters?job=qa-guru-app-tests&token=$TOKEN&TAG=UI"
        env:
          TOKEN: ${{ secrets.JENKINS_TOKEN }}
