name: frontend_deploy_test
on:
  push:
    branches:
      - develop
jobs:
  checkout:
    runs-on: stage-runner

    steps:
      - uses: actions/checkout@v4

  yarn-and-node:
    runs-on: stage-runner
    needs: checkout
    steps:
      - name: Use Node.js 18.x
        uses: actions/setup-node@v4
        with:
          node-version: 18.x
      - name: Run install
        uses: borales/actions-yarn@v4
        with:
          cmd: install # will run `yarn install` command
      - name: Run build
        uses: borales/actions-yarn@v4
        with:
          cmd: build # will run `yarn build` command
      - name: Deploy step 1
        run: rm -rf /var/www/app-stage.qa.guru/html/*
      #            cp -r dist/* /var/www/app.qa.guru/html/
      - name: Deploy step 2
        run:
          #            rm -rf /var/www/app.qa.guru/html/*
          cp -r dist/* /var/www/app-stage.qa.guru/html/
