name: frontend_deploy_prod
on:
  push:
    branches:
      - main
jobs:
  yarn-and-node:
    runs-on: prod-runner
    env:
      HUSKY: "0"
    steps:
      - uses: actions/checkout@v7
      - name: Use Node.js 26
        uses: actions/setup-node@v6
        with:
          node-version: 26
      - name: Run install
        uses: borales/actions-yarn@v4
        with:
          cmd: install
      - name: Run build
        uses: borales/actions-yarn@v4
        with:
          cmd: build
      - name: Deploy step 1
        run: rm -rf /var/www/learn.qa.guru/html/*
      - name: Deploy step 2
        run: cp -r dist/* /var/www/learn.qa.guru/html/
