name: ter4_frontend_deploy_test
on:
  push:
    branches: 
      - main
jobs:
  checkout:
    runs-on: self-hosted
    
    steps:
      - uses: actions/checkout@v1
  
  deploy:
    runs-on: self-hosted
    needs: checkout
    steps:  
      - name: deploy
        run: |
          pwd
          export NVM_DIR=/home/devops/.nvm
#          nvm --version
          corepack enable
          yarn
#          yarn build
