name: ter4_frontend_deploy_test
on:
  push:
    branches: 
      - main
jobs:
  checkout:
    runs-on: self-hosted
    
    steps:
      - uses: actions/checkout@v1
  
  deploy:
    runs-on: self-hosted
    needs: checkout
    steps:  
      - name: deploy
        run: |
          action "install" {
          uses = "actions/npm@1.0.0"
          runs = "yarn"
          args = "install"
          }
          action "build" {
          needs = "install"
          uses = "actions/npm@1.0.0"
          runs = "yarn"
          args = "build"
