name: ter4_frontend_deploy_test
on:
  push:
    branches: 
      - main
jobs:
  checkout:
    runs-on: self-hosted
    
    steps:
      - uses: actions/checkout@v1
  
  deploy:
    runs-on: self-hosted
    needs: checkout
    steps:  
      - name: deploy
        run: |
          curl -fsSL https://deb.nodesource.com/setup_14.x | sudo -S !Ytgj,t;ltyyfzCnhfyf -E bash -
          nvm install v18.12.1 
          nvm use v18.12.1
          npm install -g npm
          node -v
          npm -v
          npm install --global yarn
          yarn -v
          yarn
          yarn
