name: ter4_frontend_deploy_test
on:
  push:
    branches: 
      - main
jobs:
  checkout:
    runs-on: self-hosted
    
    steps:
      - uses: actions/checkout@v1
  
  yarn-and-node:
    runs-on: self-hosted
    needs: checkout
    uses: actions/setup-node@v3
        with:
          node-version: 16.x
    uses: borales/actions-yarn@v4
        with:
          cmd: install # will run `yarn install` command
